print("High Performance Computing Credits - 4")
print("Devops Credits - 3")
print("Software Project Management Credits - 3")
print("Environment Credits - 3")
print("Undergrad Credits - 1")
print("Capstone Credits - 1")
print("Career Skills Credits - 3")
